### PR TITLE
Added new features for Q1 2016 for RadScheduleView, RadComboBox, RadA…

### PR DESCRIPTION
**Pull request by APopatanasov**
…utoCompleteBox and RadDateTimePicker

### CODE REVIEW

**Comment by erikruth** [comment]
Can you give me a link to the articles you want me to edit? I'm only seeing an option to Merge pull request.

**Comment by APopatanasov** [comment]
Hmmm Erik....could you please check if you could edit the articles from the button shown in the image:
gitchange

I could hot provide you with links to the articles because they only exist in my repository named "X3DocumentationForQ12016" and they should become live when Q1 gets released.

**Comment by erikruth** [comment]
Unfortunately no, I don't see that edit button. Here is what I see.

image

**Comment by APopatanasov** [comment]
Erik, you have probably clicked the "Commit" tab ....commits could not be edited ...could you please, click the "Files changed" tab and let me know if the "Edit" button is now visible....
git

**Comment by APopatanasov** [comment]
Hi Erik, I will close this pull request (it is really a big one) and I will break it into small ones...also some of the changed files needs to be reverted as were not able to finish some the features we planned for Q1 2016....sorry about that if you have already started working on it :crying_cat_face:

**Pull request closed without merging**
